import React,{useState,useEffect,useRef} from 'react';
import {View,Text,Pressable,TextInput,ScrollView,Modal,StyleSheet,ActivityIndicator,Platform} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {findMatches,positiveInterests,type Profile,type Match} from '../shared/matching';
import {groupPlans,interestScore} from '../shared/grouping';
import {browserSemantic} from './semantic-web';
export type Assignment={size:number;selected:string[];groups:string[][];unassigned:string[]};
type Props={visible:boolean;people:Profile[];onClose:()=>void;onConfirm:(plan:Assignment)=>Promise<void>;canConfirm:boolean;Avatar:React.ComponentType<{p:Profile;size?:number}>;confirmed?:Assignment|null};
const titles={cohesion:'접점 우선',balance:'인원 균형 우선',coverage:'연결 범위 우선'};
export default function GroupPlanner({visible,people,onClose,onConfirm,canConfirm,Avatar,confirmed}:Props){
 const [stage,setStage]=useState(0),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[size,setSize]=useState(4),[useAI,setUseAI]=useState(false),[matches,setMatches]=useState<Match[]>([]),[planIndex,setPlanIndex]=useState(0),[detail,setDetail]=useState<number|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');const abort=useRef<AbortController|null>(null);
 const context=JSON.stringify(people.map(p=>({id:p.id,interests:p.interests})));
 useEffect(()=>{abort.current?.abort();setBusy(false);setStage(0);setSelected(confirmed?.selected.filter(id=>people.some(p=>p.id===id))||people.map(p=>p.id));setSearch('');setSize(confirmed?.size||4);setError('');setDetail(null);},[visible,context]);
 useEffect(()=>()=>abort.current?.abort(),[]);
 const chosen=people.filter(p=>selected.includes(p.id)),plans=groupPlans(chosen,matches,size),plan=plans[planIndex]||plans[0];
 async function analyze(){setBusy(true);setError('');setStage(2);const controller=new AbortController();abort.current=controller;try{setProgress('선택한 사람들의 공통 관심사를 비교하고 있어요');let ms=findMatches(chosen);if(useAI){if(Platform.OS!=='web')throw new Error('AI 의미 비교는 웹에서 실행해주세요.');ms=[...ms,...await browserSemantic(chosen,setProgress,controller.signal)];}if(controller.signal.aborted)return;setMatches(ms);setProgress('취향의 접점으로 편성안을 계산하고 있어요');setPlanIndex(0);setDetail(null);setStage(3);}catch(e:any){if(!controller.signal.aborted){setError(e.message);setStage(1);}}finally{setBusy(false);abort.current=null;}}
 function close(){abort.current?.abort();onClose();}
 const toggle=(id:string)=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
 const group=detail!==null?plan?.groups[detail]:null;
 return <Modal visible={visible} animationType="slide" onRequestClose={close}><SafeAreaView style={s.safe}><View style={s.shell}><View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="편성 화면 닫기" onPress={close}><Ionicons name="close-outline" size={26}/></Pressable><Text style={s.title}>{group?'테이블 상세':stage===3?'추천 편성안':'모임 편성하기'}</Text><Text style={s.meta}>{stage<2?`${stage+1} / 2`:''}</Text></View><ScrollView contentContainerStyle={s.body} keyboardShouldPersistTaps="handled">
 {error&&<Text style={s.error}>{error}</Text>}
 {stage===0&&<><Text style={s.heading}>누구와 함께할까요?</Text><Text style={s.copy}>이 모임에서 편성할 사람을 선택해주세요.</Text><TextInput accessibilityLabel="편성 참여자 검색" style={s.input} value={search} onChangeText={setSearch} placeholder="이름 검색"/><View style={s.between}><Text style={s.label}>{selected.length}명 선택</Text><Pressable accessibilityRole="button" onPress={()=>setSelected(selected.length===people.length?[]:people.map(p=>p.id))}><Text style={s.link}>{selected.length===people.length?'선택 해제':'전체 선택'}</Text></Pressable></View>{people.filter(p=>p.name.toLowerCase().includes(search.trim().toLowerCase())).map(p=><Pressable accessibilityRole="checkbox" accessibilityState={{checked:selected.includes(p.id)}} accessibilityLabel={`${p.name} 참여자 선택`} key={p.id} style={s.person} onPress={()=>toggle(p.id)}><Avatar p={p} size={48}/><View style={{flex:1}}><Text style={s.label}>{p.name}</Text><Text style={s.meta}>{positiveInterests(p).slice(0,3).map(t=>t.label).join(' · ')||'공유한 취향이 없어요'}</Text></View><Ionicons name={selected.includes(p.id)?'checkbox':'square-outline'} size={24} color={selected.includes(p.id)?'#171717':'#999'}/></Pressable>)}</>}
 {stage===1&&<><Text style={s.heading}>몇 명씩 모일까요?</Text><Text style={s.copy}>{chosen.length}명이 함께해요.</Text><View style={s.row}>{[3,4,5].map(n=><Pressable key={n} accessibilityRole="radio" accessibilityState={{checked:size===n}} onPress={()=>setSize(n)} style={[s.option,size===n&&s.active]}><Text style={[s.label,size===n&&s.white]}>{n}명</Text></Pressable>)}</View><View style={s.card}><Text style={s.label}>최대 {size}명 · 최소 {Math.ceil(chosen.length/size)}개 테이블</Text><Text style={s.meta}>공유한 취향의 접점을 우선해요. 접점이 부족하면 작은 테이블이나 배정 보류가 생길 수 있어요.</Text></View><Pressable accessibilityRole="checkbox" accessibilityState={{checked:useAI}} style={s.person} onPress={()=>setUseAI(!useAI)}><Ionicons name={useAI?'checkbox':'square-outline'} size={24}/><View style={{flex:1}}><Text style={s.label}>AI 의미 비교도 함께 사용</Text><Text style={s.meta}>다르게 표현한 관심사도 비교해요. 첫 실행에 AI 모델 약 614MB를 다운로드해요.</Text></View></Pressable></>}
 {stage===2&&<View style={s.loading}><ActivityIndicator color="#171717" size="large"/><Text style={s.label}>{progress}</Text><Text style={s.meta}>공유한 취향만 사용합니다.</Text></View>}
 {stage===3&&!group&&<><Text style={s.heading}>함께하기 좋은 조합</Text><Text style={s.copy}>{plans.length}개의 서로 다른 편성안을 찾았어요.</Text>{plans.length>0&&<><View style={s.row}>{plans.map((p,i)=><Pressable key={p.mode} accessibilityRole="tab" accessibilityState={{selected:plan===p}} onPress={()=>setPlanIndex(i)} style={[s.option,plan===p&&s.active]}><Text style={[s.label,plan===p&&s.white]}>추천 {i+1}</Text><Text style={[s.meta,plan===p&&s.white]}>{p.score}점</Text></Pressable>)}</View><View style={s.card}><Text style={s.label}>{titles[plan.mode]}</Text><View style={[s.between,{marginTop:12}]}><Text style={s.copy}>편성 점수 {plan.score}</Text><Text style={s.copy}>최저 테이블 {plan.minScore}</Text></View><Text style={s.meta}>테이블 간 점수 차이 {plan.range}점 · {selected.length-plan.unassigned.length}/{selected.length}명 배정</Text></View>{plan.groups.map((g,i)=>{const members=chosen.filter(p=>g.ids.includes(p.id));return <Pressable key={g.ids.join(',')} accessibilityRole="button" accessibilityLabel={`테이블 ${i+1} 상세 보기`} style={s.card} onPress={()=>setDetail(i)}><View style={s.between}><Text style={s.label}>테이블 {i+1} · {g.ids.length}명</Text><Text style={s.link}>{Math.round(g.score*100)}점</Text></View><View style={s.row}>{members.slice(0,4).map(p=><Avatar p={p} size={36} key={p.id}/>)}</View><Text style={s.copy}>{members.slice(0,3).map(p=>p.name).join(' · ')}{members.length>3?` 외 ${members.length-3}명`:''}</Text>{g.interests.map(m=><View key={m.id} style={s.between}><Text style={s.meta}>#{m.label}</Text><Text style={s.meta}>{interestScore(m,members)}점</Text></View>)}<Text style={s.link}>상세 보기</Text></Pressable>})}{plan.unassigned.length>0&&<View style={s.card}><Text style={s.label}>접점을 더 찾아볼 사람 · {plan.unassigned.length}명</Text><Text style={s.copy}>{chosen.filter(p=>plan.unassigned.includes(p.id)).map(p=>p.name).join(' · ')}</Text></View>}<Text style={s.meta}>점수는 공유 취향의 연결 정도를 나타내요. 현재는 접점 기반 편성으로 계산하며, 관계 성공 확률이나 전역 최적해를 뜻하지 않아요.</Text></>}{!plans.length&&<View style={s.card}><Text style={s.label}>아직 편성할 접점이 부족해요.</Text><Text style={s.copy}>관심사를 더 등록하거나 참여자를 바꿔보세요.</Text></View>}</>}
 {group&&<><Pressable accessibilityRole="button" onPress={()=>setDetail(null)}><Text style={s.link}>편성안으로 돌아가기</Text></Pressable><Text style={s.heading}>테이블 {detail!+1}</Text><Text style={s.label}>그룹 점수 {Math.round(group.score*100)}</Text><Text style={s.meta}>구성원끼리 공유 취향이 연결되는 정도의 평균이에요.</Text>{chosen.filter(p=>group.ids.includes(p.id)).map(p=><View key={p.id} style={s.person}><Avatar p={p}/><Text style={s.label}>{p.name}</Text></View>)}<Text style={s.heading}>공통 관심사 Top-3</Text>{group.interests.map(m=><View key={m.id} style={s.card}><View style={s.between}><Text style={s.label}>{m.label}</Text><Text style={s.link}>{interestScore(m,chosen.filter(p=>group.ids.includes(p.id)))}점</Text></View><Text style={s.copy}>{m.reason}</Text>{m.evidence.filter(e=>group.ids.includes(e.profile)).map((e,i)=><View key={i} style={{gap:4}}><Text style={s.label}>{chosen.find(p=>p.id===e.profile)?.name}</Text><Text style={s.meta}>등록한 취향 · {e.label}</Text></View>)}</View>)}</>}
 </ScrollView><View style={s.footer}>{stage===0&&<Action disabled={selected.length<3} onPress={()=>setStage(1)}>다음 · {selected.length}명</Action>}{stage===1&&<><Action secondary onPress={()=>setStage(0)}>참여자 다시 선택</Action><Action disabled={busy} onPress={analyze}>그룹 추천하기</Action></>}{stage===2&&<Action secondary onPress={()=>{abort.current?.abort();setStage(1);}}>분석 중단</Action>}{stage===3&&!group&&<><Action secondary onPress={()=>setStage(0)}>조건 다시 설정</Action>{plan&&<Action disabled={busy||!canConfirm} onPress={async()=>{setBusy(true);setError('');try{await onConfirm({size,selected,groups:plan.groups.map(g=>g.ids),unassigned:plan.unassigned});close();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'저장 중…':canConfirm?'이 편성으로 결정':'모임을 만든 사람이 확정할 수 있어요'}</Action>}</>}</View></View></SafeAreaView></Modal>;
}
function Action({children,onPress,disabled=false,secondary=false}:{children:React.ReactNode;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.action,secondary&&s.secondary,disabled&&{opacity:.45}]}><Text style={[s.label,!secondary&&s.white]}>{children}</Text></Pressable>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'white'},shell:{flex:1,maxWidth:520,width:'100%',alignSelf:'center'},header:{height:68,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:24,borderBottomWidth:1,borderColor:'#EAEAEA'},title:{fontSize:19,fontWeight:'700'},body:{padding:24,gap:18,paddingBottom:32},heading:{fontSize:25,fontWeight:'700',lineHeight:34,marginTop:8},copy:{fontSize:16,lineHeight:25,color:'#666'},meta:{fontSize:13,lineHeight:21,color:'#777'},label:{fontSize:15,lineHeight:23,fontWeight:'600',color:'#171717'},link:{fontSize:14,lineHeight:22,fontWeight:'600',color:'#171717'},row:{flexDirection:'row',gap:10,alignItems:'center'},between:{flexDirection:'row',justifyContent:'space-between',gap:12,alignItems:'center'},input:{backgroundColor:'#F7F7F7',borderRadius:14,padding:15,fontSize:16},person:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:14,borderBottomWidth:1,borderColor:'#EAEAEA'},option:{flex:1,alignItems:'center',padding:14,gap:4,borderWidth:1,borderColor:'#EAEAEA',borderRadius:14},active:{backgroundColor:'#171717'},white:{color:'white'},card:{padding:20,borderRadius:19,backgroundColor:'#F7F7F7',gap:12},loading:{paddingVertical:80,alignItems:'center',gap:22},footer:{padding:20,gap:10,borderTopWidth:1,borderColor:'#EAEAEA'},action:{padding:15,alignItems:'center',backgroundColor:'#171717',borderRadius:14},secondary:{backgroundColor:'#F7F7F7'},error:{fontSize:14,color:'#B14335',padding:12,backgroundColor:'#FFF1ED',borderRadius:12}});
