import React,{useEffect,useState,useRef} from 'react';
import {View,Text,Pressable,TextInput,ScrollView,Modal,StyleSheet,ActivityIndicator,Platform} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import type {Interest,Preference} from '../shared/matching';
import {preferenceNames,canonical} from '../shared/matching';
type RecordItem={id:string;title:string;text:string;url?:string};
export default function ImportsScreen({visible,token,linkedin,onClose,onApply}:{visible:boolean;token:string;linkedin:string;onClose:()=>void;onApply:(items:Interest[])=>void}){
 const [state,setState]=useState<any>(null),[provider,setProvider]=useState('youtube'),[playlists,setPlaylists]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[subs,setSubs]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[url,setUrl]=useState(''),[text,setText]=useState(''),[careerText,setCareerText]=useState(''),[ocrProgress,setOcrProgress]=useState(''),[mine,setMine]=useState(false),[consent,setConsent]=useState(false),[aiConsent,setAiConsent]=useState(false),[preference,setPreference]=useState<Preference>('explore'),[candidates,setCandidates]=useState<Interest[]>([]),[chosen,setChosen]=useState<string[]>([]),[picked,setPicked]=useState<string[]>([]);
 const generation=useRef(0),controller=useRef<AbortController|null>(null);
 const API=process.env.EXPO_PUBLIC_API_URL||'';
 async function request(path:string,body?:any){const r=await fetch(API+'/api/integrations/'+path,{signal:controller.current?.signal,method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error||'가져오지 못했어요.');return b;}
 async function load(){const version=generation.current;const s=await request('state');if(version!==generation.current)return;setState(s);if(s.youtube.connected){const p=await request('youtube/playlists');if(version===generation.current)setPlaylists(p.playlists);}}
 async function run(fn:()=>Promise<void>){const version=generation.current;setBusy(true);setError('');try{await fn();}catch(e:any){if(version===generation.current&&e.name!=='AbortError')setError(e.message);}finally{if(version===generation.current){setBusy(false);setOcrProgress('');}}}
 useEffect(()=>{generation.current++;controller.current?.abort();controller.current=new AbortController();setState(null);setPlaylists([]);setSelected([]);setSubs(false);setBusy(false);setMine(false);setCandidates([]);setChosen([]);setPicked([]);setText('');setCareerText('');setOcrProgress('');setUrl(linkedin?'https://www.linkedin.com/in/'+encodeURIComponent(linkedin)+'/':'');setConsent(false);setAiConsent(false);if(visible)run(load);return()=>{generation.current++;controller.current?.abort();};},[visible,token]);
 const records:RecordItem[]=state?.imports?.[provider]?.records||[];
 function switchProvider(p:string){setProvider(p);setPicked([]);setText('');setCandidates([]);setChosen([]);setError('');setPreference(p==='linkedin'?'explore':'like');}
 async function file(){if(Platform.OS!=='web')throw Error('사진 인식은 웹에서 사용할 수 있어요.');const version=generation.current;const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';const f=await new Promise<File|null>(resolve=>{input.onchange=()=>resolve(input.files?.[0]||null);input.oncancel=()=>resolve(null);input.click();});if(!f||version!==generation.current)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('PNG·JPG·WebP 이미지를 선택해주세요.');if(f.size>6*1024*1024)throw Error('이미지는 6MB 이하로 올려주세요.');const w=window as any;if(!w.saiReadProfileImage){await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.type='module';script.src='/ocr/read-profile.js';script.onload=()=>resolve();script.onerror=()=>reject(Error('사진 인식을 준비하지 못했어요. 다시 시도해주세요.'));document.head.appendChild(script);});}const content=await w.saiReadProfileImage(f,(message:string)=>{if(version===generation.current)setOcrProgress(message);},controller.current?.signal);if(version!==generation.current)return;if(!content.trim())throw Error('글자를 찾지 못했어요. 글자가 선명한 이미지를 선택해주세요.');if(content.length>20000)throw Error('전공·소개 부분만 담은 이미지를 선택해주세요.');setCareerText(content);setProvider('linkedin');setCandidates([]);
 }

 async function importText(){if(!careerText.trim())throw Error('전공·소개를 입력해주세요.');if(careerText.length>20000)throw Error('20,000자 이내로 입력해주세요.');const records=[];for(let i=0;i<careerText.length;i+=1600)records.push({id:'career-'+i,title:'내 전공·소개',text:careerText.slice(i,i+1600)});await request('linkedin/import',{records});await load();setCareerText('');setPicked([]);}
 async function analyze(){const version=generation.current;const r=await fetch(API+'/api/app',{signal:controller.current?.signal,method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action:'parseText',text,preference,aiConsent})});const b=await r.json();if(!r.ok)throw Error(b.error);if(version!==generation.current)return;setCandidates(b.candidates);setChosen([]);if(!b.candidates.length)throw Error('관심사 이름을 찾지 못했어요. 분석할 문장을 구체적으로 적어주세요.');}
 const toggle=(id:string)=>setPicked(picked.includes(id)?picked.filter(x=>x!==id):[...picked,id]);
 return <Modal visible={visible} animationType="slide" onRequestClose={()=>!busy&&onClose()}><SafeAreaView style={s.safe}><View style={s.shell}><View style={s.header}><Text style={s.title}>내 활동에서 취향 찾기</Text><Pressable disabled={busy} accessibilityRole="button" onPress={onClose}><Text>닫기</Text></Pressable></View><ScrollView contentContainerStyle={s.body} keyboardShouldPersistTaps="handled"><Text style={s.copy}>가져온 자료는 나만 볼 수 있어요. 확인하고 선택한 관심사만 프로필에 추가해요.</Text><View style={s.row}>{['youtube','linkedin'].map(p=><Pressable accessibilityRole="tab" accessibilityState={{selected:provider===p}} key={p} style={[s.option,provider===p&&s.active]} disabled={busy} onPress={()=>switchProvider(p)}><Text style={provider===p?s.white:s.label}>{p==='youtube'?'YouTube':'LinkedIn'}</Text></Pressable>)}</View>{error&&<Text style={s.error}>{error}</Text>}{busy&&<View style={s.row}><ActivityIndicator/><Text style={s.copy}>{ocrProgress||'처리하고 있어요…'}</Text></View>}
 {provider==='youtube'&&<View style={s.card}><Text style={s.title}>내 재생목록과 구독 채널</Text><Text style={s.copy}>연결할 때 한 번 승인하면 다음에는 바로 가져올 수 있어요. 영상 제목과 설명에서 관심사를 찾아요.</Text>{!state?.youtube.connected?<><Text style={s.copy}>YouTube 읽기 권한만 사용합니다.</Text><Action disabled={busy||!state?.youtube.configured} onPress={()=>run(async()=>{const r=await request('youtube/start',{});window.location.assign(r.url);})}>Google 계정으로 YouTube 연결</Action>{state&&!state.youtube.configured&&<Text style={s.copy}>YouTube 연결 설정을 준비하고 있어요.</Text>}</>:<>{playlists.length===0&&<Text style={s.copy}>재생목록이 없어요. 구독 채널을 가져올 수 있어요.</Text>}{playlists.map(p=><Check key={p.id} checked={selected.includes(p.id)} disabled={busy} onPress={()=>setSelected(selected.includes(p.id)?selected.filter(x=>x!==p.id):[...selected,p.id])}>{p.title} · {p.count}개</Check>)}<Check checked={subs} disabled={busy} onPress={()=>setSubs(!subs)}>구독 채널도 가져오기</Check><Text style={s.copy}>최대 10개 재생목록·영상 100개·구독 채널 50개를 가져옵니다.</Text><Action disabled={busy||(!selected.length&&!subs)} onPress={()=>run(async()=>{await request('youtube/import',{playlistIds:selected,includeSubscriptions:subs});await load();setPicked([]);setCandidates([]);})}>선택한 활동 가져오기</Action><Action secondary disabled={busy} onPress={()=>run(async()=>{await request('disconnect',{provider:'youtube'});await load();setCandidates([]);setText('');setPlaylists([]);})}>연결 해제·가져온 자료 삭제</Action></>}</View>}
 {provider==='linkedin'&&<><View style={s.card}><Text style={s.title}>내 공개 프로필에서 가져오기</Text><Text style={s.copy}>공개된 학력·전공·소개·전문 분야를 가져와 관심사 후보를 찾아요. LinkedIn 비밀번호는 사용하지 않아요.</Text><TextInput accessibilityLabel="가져올 LinkedIn 링크" style={s.input} value={url} onChangeText={setUrl} placeholder="https://www.linkedin.com/in/내아이디/" autoCapitalize="none"/><Check checked={mine} disabled={busy} onPress={()=>setMine(!mine)}>내 프로필 링크예요</Check><Check checked={consent} disabled={busy} onPress={()=>setConsent(!consent)}>이 링크를 Bright Data에 보내 공개 정보를 가져오는 데 동의해요</Check><Action disabled={busy||!mine||!consent||!state?.linkedin?.configured} onPress={()=>run(async()=>{await request('linkedin/start',{url,isMine:mine,consent});await load();})}>링크에서 가져오기</Action>{state&&!state.linkedin?.configured&&<Text style={s.copy}>링크 자동 가져오기는 연결 설정 후 사용할 수 있어요. 아래에서 사진이나 소개를 바로 추가할 수 있어요.</Text>}{state?.imports?.['linkedin-job']&&<Action secondary disabled={busy} onPress={()=>run(async()=>{const r=await request('linkedin/result',{});if(r.status==='running')throw Error('아직 가져오는 중이에요. 잠시 후 결과를 확인해주세요.');await load();setPicked([]);setCandidates([]);})}>가져오기 결과 확인</Action>}</View><View style={s.card}><Text style={s.title}>소개·전공 직접 가져오기</Text><Action secondary disabled={busy} onPress={()=>run(file)}>프로필 사진에서 글자 읽기 (OCR)</Action><TextInput accessibilityLabel="LinkedIn 전공과 소개" multiline maxLength={20000} style={[s.input,{minHeight:120}]} value={careerText} onChangeText={setCareerText} placeholder="전공, 학력, 소개, 관심 분야를 붙여넣어주세요."/><Action disabled={busy||!careerText.trim()} onPress={()=>run(importText)}>내용 확인하고 가져오기</Action><Text style={s.copy}>연락처 등 개인정보는 제외해주세요. 이미지는 기기에서 읽으며 서버에 업로드하지 않아요. 인식한 글자를 확인·수정한 뒤 가져와주세요.</Text>{records.length>0&&<Action secondary disabled={busy} onPress={()=>run(async()=>{await request('disconnect',{provider:'linkedin'});await load();setText('');setPicked([]);setCandidates([]);})}>가져온 자료 삭제</Action>}</View></>}
 {records.length>0&&<View style={s.card}><Text style={s.title}>가져온 자료 · {records.length}개</Text><Text style={s.copy}>분석할 자료를 선택한 뒤 문장을 확인·수정해주세요.</Text>{records.map(r=><View key={r.id}><Check checked={picked.includes(r.id)} disabled={busy} onPress={()=>toggle(r.id)}>{r.title}</Check>{picked.includes(r.id)&&<Text style={s.copy}>{r.text.slice(0,240)}</Text>}</View>)}<Action secondary disabled={busy||!picked.length} onPress={()=>{setText(records.filter(r=>picked.includes(r.id)).map(r=>r.title+'\n'+r.text).join('\n').slice(0,1000));setCandidates([]);setChosen([]);}}>선택한 자료로 분석 문장 만들기</Action><Text style={s.copy}>분석 문장은 최대 1,000자예요. 아래에서 전공·관심 분야만 남겨주세요.</Text></View>}
 {records.length>0&&<View style={s.card}><Text style={s.title}>나의 관심사로 정리하기</Text><TextInput accessibilityLabel="가져온 자료 분석 문장" multiline maxLength={1000} value={text} onChangeText={v=>{setText(v);setCandidates([]);setChosen([]);}} style={[s.input,{minHeight:130}]}/><View style={s.row}>{(['like','avoid','explore'] as Preference[]).map(p=><Pressable accessibilityRole="tab" key={p} onPress={()=>{setPreference(p);setCandidates([]);setChosen([]);}} style={[s.option,preference===p&&s.active]}><Text style={preference===p?s.white:s.label}>{preferenceNames[p]}</Text></Pressable>)}</View><Text style={s.copy}>학력·전공이 있다고 좋아한다고 단정하지 않아요. 관심사로 추가할 때 내 선호를 선택해주세요.</Text><Check checked={aiConsent} disabled={busy} onPress={()=>setAiConsent(!aiConsent)}>이 문장을 Gemini로 보내 정리하는 데 동의해요</Check><Text style={s.copy}>무료 API 입력·출력은 Google의 제품 개선에 사용될 수 있어요.</Text><Action disabled={busy||!aiConsent||!text.trim()} onPress={()=>run(analyze)}>관심사 후보 정리하기</Action>{candidates.map(t=><Check key={t.id} checked={chosen.includes(t.id)} disabled={busy} onPress={()=>setChosen(chosen.includes(t.id)?chosen.filter(id=>id!==t.id):[...chosen,t.id])}>{t.label} · {t.category}</Check>)}{candidates.length>0&&<><Action disabled={busy||!chosen.length} onPress={()=>{const seen=new Set();onApply(candidates.filter(t=>chosen.includes(t.id)&&!seen.has(canonical(t.label))&&seen.add(canonical(t.label))).map(t=>({...t,shared:false})));}}>선택한 관심사 추가</Action><Text style={s.copy}>추가한 관심사는 기본 비공개예요. 프로필에서 선호와 공유 설정을 확인하고 저장해주세요.</Text></>}</View>}
 </ScrollView></View></SafeAreaView></Modal>;
}
function Check({checked,onPress,children,disabled=false}:any){return <Pressable accessibilityRole="checkbox" accessibilityState={{checked}} disabled={disabled} onPress={onPress} style={s.check}><Text style={s.label}>{checked?'☑':'□'} {children}</Text></Pressable>;}
function Action({onPress,children,disabled=false,secondary=false}:any){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.action,secondary&&{backgroundColor:'#EAEAEA'},disabled&&{opacity:.4}]}><Text style={secondary?s.label:s.white}>{children}</Text></Pressable>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'white'},shell:{flex:1,maxWidth:520,width:'100%',alignSelf:'center'},header:{padding:22,borderBottomWidth:1,borderColor:'#EAEAEA',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:18,fontWeight:'700',lineHeight:28},body:{padding:22,gap:20},card:{backgroundColor:'#F7F7F7',padding:20,borderRadius:18,gap:14},copy:{fontSize:14,color:'#777',lineHeight:23},label:{fontSize:14,fontWeight:'600',lineHeight:22},row:{flexDirection:'row',gap:8},option:{flex:1,padding:12,alignItems:'center',borderRadius:12,backgroundColor:'#EAEAEA'},active:{backgroundColor:'#171717'},white:{color:'white',fontWeight:'600',fontSize:14,lineHeight:22},check:{paddingVertical:10},action:{backgroundColor:'#171717',padding:14,borderRadius:12,alignItems:'center'},input:{backgroundColor:'white',padding:14,borderRadius:12,fontSize:15,lineHeight:23},error:{color:'#B14335',backgroundColor:'#FFF1ED',padding:12,borderRadius:10}});
