import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {api} from '../backend/api.mjs';
import {seal,unseal,digest,integrationRoute} from '../backend/integrations.mjs';
import {extractGemini} from '../backend/gemini.mjs';
import {discoverBridgeTopics} from '../backend/bridge-topics.mjs';
import {linkedinRecords,resultLinkedin} from '../backend/linkedin.mjs';
import {ensureProfileColumns} from '../backend/profile-migration.mjs';
async function fixture(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');const DB={prepare(q){let args=[];const st=sql.prepare(q);return{bind(...x){args=x;return this;},async first(){return st.get(...args)||null;},async all(){return{results:st.all(...args)};},async run(){return st.run(...args);}};},async batch(statements){sql.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort()){if(file.startsWith('0001_'))await ensureProfileColumns(DB);sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));}
 for(const id of ['a','b','c','d']){sql.prepare('INSERT INTO accounts(owner,username,password_hash,created) VALUES(?,?,?,?)').run(id,id,'fixture','2026-01-01');sql.prepare('INSERT INTO profiles(id,owner,name,bio,interests,color,created) VALUES(?,?,?,?,?,?,?)').run(id,id,id,'',JSON.stringify([{id:'jazz',label:'재즈',category:'음악',shared:true,preference:'like'}]),'#111',new Date().toISOString());sql.prepare('INSERT INTO sessions(token_hash,owner,created) VALUES(?,?,?)').run(await digest(id+'-token'),id,new Date().toISOString());}
 const env={DB,YOUTUBE_CLIENT_ID:'fixture-client',YOUTUBE_CLIENT_SECRET:'fixture-secret',TOKEN_ENCRYPTION_KEY:btoa('a'.repeat(32)),INTEGRATION_ORIGIN:'http://localhost:8788',GEMINI_API_KEY:'fixture-ai-key'};return{DB,sql,env};}
const req=(path,body,owner='a',cookie='')=>new Request('http://localhost:8788'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+owner+'-token','Content-Type':'application/json',cookie},...(body?{body:JSON.stringify(body)}:{})});
test('Gemini bridge API uses stored shared interests, explicit consent and current friendship access',async()=>{
 const {env,sql}=await fixture();sql.prepare("INSERT INTO friendships VALUES('a','b','accepted')").run();
 sql.prepare('UPDATE profiles SET interests=? WHERE id=?').run(JSON.stringify([{id:'anime',label:'애니메이션',category:'콘텐츠',shared:true},{id:'private',label:'secret-interest',category:'기타',shared:false}]),'a');
 sql.prepare('UPDATE profiles SET interests=? WHERE id=?').run(JSON.stringify([{id:'travel',label:'일본 여행',category:'여행',shared:true}]),'b');
 let calls=0;env.AI_FETCH=async(url,init)=>{calls++;const body=JSON.parse(init.body);const input=body.contents[0].parts[0].text;assert(!input.includes('secret-interest'));assert(!input.includes('username'));return Response.json({candidates:[{content:{parts:[{text:JSON.stringify({topics:[{label:'애니메이션 성지순례',reason:'작품과 여행을 연결하는 주제입니다.',links:[{profile:'a',interest:'anime',connection:'애니메이션 장소를 이야기해볼 수 있어요.'},{profile:'b',interest:'travel',connection:'여행 테마를 이야기해볼 수 있어요.'}]}]})}]}}]});};
 const post=body=>api(req('/api/app',body),env);
 assert.equal((await post({action:'bridgeTopics',profiles:['a','b']})).status,400);assert.equal(calls,0);
 assert.equal((await post({action:'bridgeTopics',profiles:['a','c'],aiConsent:true})).status,403);assert.equal(calls,0);
 const r=await post({action:'bridgeTopics',profiles:['a','b'],aiConsent:true,people:[{id:'a',interests:['fake']}]});assert.equal(r.status,200);const data=await r.json();assert.equal(data.topics.length,1);assert(!JSON.stringify(data).includes('secret-interest'));assert.equal(calls,1);
 env.AI_FETCH=async()=>{sql.prepare("DELETE FROM friendships WHERE sender='a' AND recipient='b'").run();return Response.json({candidates:[{content:{parts:[{text:'{"topics":[]}'}]}}]});};
 assert.equal((await post({action:'bridgeTopics',profiles:['a','b'],aiConsent:true})).status,403);
});
test('bridge discovery skips sufficient direct topics and rejects missing shared interests',async()=>{
 const {env}=await fixture();let calls=0;env.AI_FETCH=async()=>{calls++;return Response.json({candidates:[{content:{parts:[{text:'{"topics":[]}'}]}}]});};
 const people=['a','b'].map(id=>({id,interests:['재즈','러닝','사진'].map((label,i)=>({id:String(i),label,category:'기타',shared:true}))}));
 assert.equal((await discoverBridgeTopics(env,'a',people)).reason,'enough_direct');assert.equal(calls,0);
 await assert.rejects(()=>discoverBridgeTopics(env,'a',[people[0],{id:'b',interests:[]}]));assert.equal(calls,0);
});
async function call(env,path,body,owner='a',cookie=''){return integrationRoute(req(path,body,owner,cookie),env,{owner,sessionHash:await digest(owner+'-token')});}
test('OAuth state, browser cookie, PKCE, single use, encrypted owner-bound token',async()=>{const {env,sql}=await fixture();let n=0;env.INTEGRATION_FETCH=async(url,init)=>{n++;assert.equal(new URLSearchParams(init.body).get('code_verifier').length,43);return Response.json({access_token:'private-access',refresh_token:'private-refresh',expires_in:3600,scope:'https://www.googleapis.com/auth/youtube.readonly'});};const start=await call(env,'/api/integrations/youtube/start',{}),u=new URL((await start.json()).url),cookie=start.headers.get('set-cookie').split(';')[0];assert.equal(u.searchParams.get('scope'),'https://www.googleapis.com/auth/youtube.readonly');assert.equal(u.searchParams.get('code_challenge_method'),'S256');const path='/api/integrations/youtube/callback?state='+u.searchParams.get('state')+'&code=fixture';assert.equal((await call(env,path,undefined,'a','sai-oauth=wrong')).headers.get('location'),'/?integration=youtube&status=failed');assert.equal(n,0);assert.equal((await call(env,path,undefined,'a',cookie)).headers.get('location'),'/?integration=youtube&status=connected');assert.equal(n,1);const stored=sql.prepare('SELECT payload FROM connected_accounts').get().payload;assert.ok(!stored.includes('private'));assert.equal((await unseal(stored,env,'a')).refresh,'private-refresh');await assert.rejects(()=>unseal(stored,env,'b'));await call(env,path,undefined,'a',cookie);assert.equal(n,1);const other=await call(env,'/api/integrations/state',undefined,'b');assert.equal((await other.json()).youtube.connected,false);const own=await call(env,'/api/integrations/state');assert.ok(!(await own.text()).includes('private-access'));});
test('logged-out session cannot complete pending OAuth',async()=>{const {env,sql}=await fixture();env.INTEGRATION_FETCH=()=>{throw Error('must not contact Google');};const s=await call(env,'/api/integrations/youtube/start',{}),u=new URL((await s.json()).url);sql.prepare('DELETE FROM sessions WHERE owner=?').run('a');const r=await call(env,'/api/integrations/youtube/callback?state='+u.searchParams.get('state')+'&code=fixture',undefined,'a',s.headers.get('set-cookie').split(';')[0]);assert.equal(r.headers.get('location'),'/?integration=youtube&status=failed');assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM connected_accounts').get().n,0);});
test('private imports, owned playlists, refreshed access cannot revive disconnect',async()=>{const {env,sql}=await fixture();sql.prepare("INSERT INTO connected_accounts VALUES(?,'youtube',?,?)").run('a',await seal({access:'old',refresh:'refresh',expires:Date.now()+3600000},env,'a'),'now');env.INTEGRATION_FETCH=async(url)=>{const u=new URL(url);if(u.pathname.endsWith('playlists'))return Response.json({items:[{id:'own',snippet:{title:'내 목록'}}]});if(u.pathname.endsWith('playlistItems'))return Response.json({items:[{contentDetails:{videoId:'video'},snippet:{title:'재즈 공연',description:'음악 듣기'}}]});throw Error('unexpected');};assert.equal((await call(env,'/api/integrations/youtube/import',{playlistIds:['other']})).status,400);assert.equal((await call(env,'/api/integrations/youtube/import',{playlistIds:['own']})).status,200);const mine=await (await call(env,'/api/integrations/state')).json(),other=await (await call(env,'/api/integrations/state',undefined,'b')).json();assert.equal(mine.imports.youtube.records[0].title,'재즈 공연');assert.equal(other.imports.youtube,undefined);sql.prepare("UPDATE connected_accounts SET payload=? WHERE owner='a'").run(await seal({access:'old',refresh:'refresh',expires:0},env,'a'));env.INTEGRATION_FETCH=async()=>{sql.prepare("DELETE FROM connected_accounts WHERE owner='a'").run();return Response.json({access_token:'new',expires_in:3600});};assert.equal((await call(env,'/api/integrations/youtube/playlists')).status,409);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM connected_accounts').get().n,0);});
test('Gemini evidence and quotas: input accepted, invented labels discarded',async()=>{const {env,sql}=await fixture();let calls=0;env.AI_FETCH=async()=>{calls++;return Response.json({candidates:[{content:{parts:[{text:'[["재즈","음악"],["축구","운동"]]'}]}}]});};const result=await extractGemini(env,'a','재즈를 좋아해','like');assert.deepEqual(result.map(t=>t.label),['재즈']);assert.equal(result[0].shared,false);assert.deepEqual(await extractGemini(env,'a','이메일: test@example.com','like'),[]);assert.equal(calls,2);sql.prepare("UPDATE ai_usage SET used=35 WHERE key LIKE '%:a'").run();await assert.rejects(()=>extractGemini(env,'a','재즈를 좋아해','like'),e=>e.status===429);assert.equal(calls,2);});
test('LinkedIn returns only professional sections and jobs cannot cross owners',async()=>{const {env}=await fixture();const r=linkedinRecords({name:'개인 이름',email:'private@example.com',education:[{degree:'Computer Science'}],about:'인공지능과 디자인에 관심',interests:[{name:'Machine learning'}]},'https://www.linkedin.com/in/test/');assert.ok(r.some(x=>x.text.includes('Computer Science')));assert.ok(!JSON.stringify(r).includes('private@example.com'));assert.ok(!JSON.stringify(r).includes('개인 이름'));await assert.rejects(()=>resultLinkedin(env,'b'));});
test('only accepted friends can be invited, acceptance creates real membership',async()=>{const {env,sql}=await fixture();for(const friend of ['b','c'])sql.prepare("INSERT INTO friendships VALUES(?,?,'accepted')").run('a',friend);const plan={size:3,selected:['a','b','c'],groups:[['a','b','c']],unassigned:[]};const post=async(body,owner='a')=>api(req('/api/app',body,owner),env);assert.equal((await post({action:'createPlannedRoom',name:'모임',plan:{...plan,selected:['a','b','d'],groups:[['a','b','d']]}})).status,400);const r=await post({action:'createPlannedRoom',name:'모임',plan});assert.equal(r.status,200);const {id}=await r.json();assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM members WHERE room=?').get(id).n,1);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM room_invites WHERE room=?').get(id).n,2);const b=await api(req('/api/app',undefined,'b'),env);assert.equal((await b.json()).invites[0].id,id);await post({action:'joinRoom',id},'b');assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM members WHERE room=?').get(id).n,2);await post({action:'declineRoomInvite',id},'c');assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM room_invites WHERE room=?').get(id).n,0);});

test('example friends are isolated, idempotent and can join example groups without invites',async()=>{
 const {env,sql}=await fixture();const add=await api(req('/api/app',{action:'addExampleFriends'}),env);assert.equal(add.status,200);
 await api(req('/api/app',{action:'addExampleFriends'}),env);
 const own=await (await api(req('/api/app'),env)).json();assert.equal(own.friends.length,11);assert(own.friends.every(p=>p.isExample&&!p.name.includes('예시')&&p.interests.length>=3));
 const other=await (await api(req('/api/app',undefined,'b'),env)).json();assert.equal(other.friends.length,0);
 const selected=['a',...own.friends.slice(0,2).map(p=>p.id)];const created=await api(req('/api/app',{action:'createPlannedRoom',name:'예시 모임',plan:{size:3,selected,groups:[selected],unassigned:[]}}),env);assert.equal(created.status,200);const {id}=await created.json();assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM members WHERE room=?').get(id).n,3);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM room_invites WHERE room=?').get(id).n,0);
 assert.equal(sql.prepare("SELECT COUNT(*) AS n FROM accounts WHERE owner LIKE 'example:%'").get().n,0);
});
